ecommerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls'))
]

pages/urls.py
from django.urls import path

from .views import AboutPageView, HomePageView

app_name = 'pages'


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about')
]

pages/views.py
from django.views.generic import TemplateView


class AboutPageView(TemplateView):
    template_name = 'about.html'


class HomePageView(TemplateView):
    template_name = 'home.html'

templates/about.html
{% extends "shared/base.html" %}

{% block content %}
<h1 class="font-weight-bold">About us</h1>
<p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, totam iure numquam quaerat amet, officiis
    accusantium dolor assumenda dolores esse dignissimos voluptatem. Commodi laborum non minima dolor illum
    reiciendis est.Temporibus delectus quam odit voluptatibus debitis nesciunt optio voluptates ut inventore porro
    perferendis, quidem magnam repellat quo ratione, quos quod? Nesciunt, in quidem. Necessitatibus sapiente ad iure
    impedit quod cumque?
</p>
<p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, totam iure numquam quaerat amet, officiis
    accusantium dolor assumenda dolores esse dignissimos voluptatem. Commodi laborum non minima dolor illum
    reiciendis est.Temporibus delectus quam odit voluptatibus debitis nesciunt optio voluptates ut inventore porro
    perferendis, quidem magnam repellat quo ratione, quos quod? Nesciunt, in quidem. Necessitatibus sapiente ad iure
    impedit quod cumque?
</p>
{% endblock %}

templates/home.html
{% extends "shared/base.html" %}

templates/shared/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Ecommerce{% endblock %}</title>
    {# Loading static files from server #}
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/ecommerce-logo.png' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container container-fluid">
            <a class="navbar-brand" href="{% url 'pages:home' %}">
                <img src="{% static 'images/ecommerce-logo.png' %}" width="30" height="30" alt="">
                Navbar
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" 
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pages:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pages:about' %}">About</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <main class="container my-3">
        {% block content %}{% endblock %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
    </script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>